### ISSUE TITLE
Create a new release after adding python3 support

### ISSUE THREAD

**Issue by lCharlie123l** [thumbor/libthumbor#18]
Hi, I noticed you recently added python3 support. Would be great if you could create a new release with these additions as I'm working on porting another component that uses this library to python 3.

Many Thanks

**Comment by dmkc** [comment]
+1

**Comment by elliottsj** [comment]
:+1:

**Comment by heynemann** [comment]
Done! https://github.com/thumbor/libthumbor/releases/tag/1.2.0

Thanks and sorry to keep you waiting!

**Comment by lCharlie123l** [comment]
Thank you!

**Comment by dmkc** [comment]
You're the best! :fireworks:
