### ISSUE TITLE
Url and Signer should be part of libthumbor

### ISSUE THREAD

**Issue by gi11es** [thumbor/libthumbor#24]
I can take care of the move, but first I want a second opinion to check that my logic is correct.

Currently, the libthumbor tests depend on thumbor, but that dependency is implicit. Specifically, tests/test_libthumbor.py imports Signer from thumbor.crypto and Url from thumbor.url

This creates an annoying circular dependency which makes packaging libthumbor difficult.

However, Signer and Url are both standalone classes. Therefore they look easy to move to libthumbor. By doing so, there would be a much cleaner separation between both modules and packaging of libthumbor would become easier.

Does this move make sense?

**Comment by gi11es** [comment]
In fact I see that forked python3 versions of those classes are already in libthumbor. Having the originals and the python3 versions in the same project should make keeping them in sync easier.

**Comment by guilhermef** [comment]
I think that would be the best solution,
since Thumbor already depends on libthumbor.

**Comment by gi11es** [comment]
Alright, I'll prepare PRs here and on Thumbor, then.

**Comment by gi11es** [comment]
PR is ready for review. I'll do the Thumbor PR once this libthumbor one has been merged.
