### ISSUE TITLE
Manual crop not working

### ISSUE THREAD

**Issue by henriquechehad** [thumbor/libthumbor#32]
In the docs refers a way to crop manually the image:
https://github.com/thumbor/thumbor/wiki/Usage#manual-crop

It's working when I use directly in URL, using this way in image size: AxB:CxD. 
Example: THUMBOR_SERVER/unsafe/0x400:1280x600/smart/IMAGE_URL

But it doesn't work when I try to use this calling [CryptoURL().generate()](https://github.com/thumbor/libthumbor/blob/8114928102ff07166ce32e6d894f30124b5e169a/libthumbor/crypto.py#L52)  passing crop_left, crop_top, crop_right, crop_bottom attributes in kwargs.

Like this example [here](https://github.com/thumbor/libthumbor/blob/8114928102ff07166ce32e6d894f30124b5e169a/libthumbor/django/views.py#L53).

Is something wrong or there is other way to do this manual crop?

**Comment by heynemann** [comment]
```
        url = self.crypto.generate(
            image_url=IMAGE_URL,
            width=300,
            height=200,
            crop=((10, 10), (200, 200)),
            filters=("brightness(20)", "contrast(10)"),
        )
````
This is what you mean? There's a test for that.
